from app.schemas.ai import (
    DailyPlanActionCopyAIResponse,
    DailyPlanCopyAIResponse,
    DailyPlanCopyInput,
    LifestyleAnalysisEndpointResponse,
    LifestyleAnalysisRequest,
    LifestyleAnalysisAIResponse,
    LifestyleAnalysisInput,
)
from app.schemas.common import ApiErrorBody, ApiFailureResponse, ApiMeta, ApiSuccessResponse
from app.schemas.internal import (
    InternalJobErrorResponse,
    InternalJobTarget,
    GenerateDailyRecommendationsJobRequest,
    GenerateDailyRecommendationsJobResponse,
)
from app.schemas.recommendation import (
    DailyPlanResponse,
    DailySummaryResponse,
    GenerateDailyPlanRequest,
    LifestyleAnalysisResponse,
    RecommendationActionResponse,
    SavingsCalendarResponse,
    SavingsSummaryResponse,
    TodayProgressResponse,
    ToggleActionRequest,
    ToggleActionDeltaResponse,
    ToggleActionResponse,
)

__all__ = [
    "ApiErrorBody",
    "ApiFailureResponse",
    "ApiMeta",
    "ApiSuccessResponse",
    "DailyPlanActionCopyAIResponse",
    "DailyPlanCopyAIResponse",
    "DailyPlanCopyInput",
    "DailyPlanResponse",
    "DailySummaryResponse",
    "GenerateDailyPlanRequest",
    "GenerateDailyRecommendationsJobRequest",
    "GenerateDailyRecommendationsJobResponse",
    "InternalJobErrorResponse",
    "InternalJobTarget",
    "LifestyleAnalysisEndpointResponse",
    "LifestyleAnalysisAIResponse",
    "LifestyleAnalysisInput",
    "LifestyleAnalysisRequest",
    "LifestyleAnalysisResponse",
    "RecommendationActionResponse",
    "SavingsCalendarResponse",
    "SavingsSummaryResponse",
    "TodayProgressResponse",
    "ToggleActionRequest",
    "ToggleActionDeltaResponse",
    "ToggleActionResponse",
]
